#!/bin/bash

for sh in /etc/profile.d/*.sh ; do
    [ -r "$sh" ] && . "$sh"
done

#Set Hostname to corresponding platform/board name based on
#the proc/device-tree
if grep -q eaik <<< cat /proc/device-tree/compatible; then
	HOSTNAME=tda4vm-sk
else
	HOSTNAME=j7-evm
fi


echo $HOSTNAME > /etc/hostname
/bin/hostname -F /etc/hostname

exit 0