#!/bin/bash

for sh in /etc/profile.d/*.sh ; do
    [ -r "$sh" ] && . "$sh"
done

#Set Hostname to corresponding platform/board name based on
#the proc/device-tree
if grep -q sk <<< cat /proc/device-tree/compatible; then
	HOSTNAME=__UPDATE__
else
	HOSTNAME=__MACHINE__
fi


echo $HOSTNAME > /etc/hostname
/bin/hostname -F /etc/hostname

exit 0